language: java


jdk:
  - openjdk8


install: true

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.m2

script:
  - mvn clean compile > /dev/null 2>&1
  - mvn org.jacoco:jacoco-maven-plugin:prepare-agent test

env:
  - CODECOV_TOKEN=${CODECOV_TOKEN}

after_success:
  - bash <(curl -s https://codecov.io/bash)